verbose = false         # Enable verbose output
use_qemu = false        # set true to use rv32 toolchain to run test in lab0/lab4/bonus1/bonu2
parallel = true         # set true to enable parallel testing
check_ssa = false       # set true to enable SSA check during IR interpretation
extra_cflags = []       # extra cflags for compiling test programs when using rv32 toolchain