# verbose = false         # Enable verbose output
# use_qemu = false        # set true to use rv32 toolchain to run test in lab0/lab4/bonus1/bonu2
# use_accipit = false     # set true to use accipit ir to test lab3
# parallel = true         # set true to enable parallel testing
# check_ssa = false       # set true to enable SSA check during IR interpretation
# precise_timing = true   # set true to enable precise timing when run with elf
timeout = 60.0          # timeout for compiling and running test programs
# extra_cflags = []       # extra cflags for compiling test programs when using rv32 toolchain